"""Adicionadas colunas diretores e nota em Filmes

Revision ID: 00851eaf9f64
Revises: a694a1300095
Create Date: 2022-07-13 19:04:34.453225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00851eaf9f64'
down_revision = 'a694a1300095'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filmes', sa.Column('diretores', sa.String(), nullable=True))
    op.add_column('filmes', sa.Column('nota', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filmes', 'nota')
    op.drop_column('filmes', 'diretores')
    # ### end Alembic commands ###
