"""Add imdb id Filmes

Revision ID: 3f11f263bb8a
Revises: 65e3e206f5ee
Create Date: 2022-07-14 12:24:23.415389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f11f263bb8a'
down_revision = '65e3e206f5ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
