"""Add diretores em Filmes

Revision ID: 6727b43a41c3
Revises: 
Create Date: 2022-07-13 18:56:28.401210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6727b43a41c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filmes', sa.Column('diretores', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filmes', 'diretores')
    # ### end Alembic commands ###
