"""Add imdb id Filmes ok

Revision ID: 6aabd1803b8b
Revises: 3f11f263bb8a
Create Date: 2022-07-14 12:24:42.306562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aabd1803b8b'
down_revision = '3f11f263bb8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
